#!/usr/bin/env python3
"""Generate the NovaGuard policy-type artifacts from the one versioned schema.

`schema/novaguard-policy.v1.json` is the single source of truth for the NovaGuard
policy contract. This script derives, from that file alone:

  * `src/policy/policy_types.generated.rs`  — the gateway's `PolicyType` enum,
    its wire/platform spellings, and its enforcement classification.
  * `<platform>/packages/api/src/routes/v1/guardrails/generated/policy-types.generated.ts`
    — the same information for the Noveum platform, plus the exact member list
    the Prisma `PolicyType` enum has to carry.
  * `<platform>/.../generated/novaguard-policy.v1.json` — a byte-identical vendored
    copy of the schema, so the platform can validate against it without a
    cross-repo checkout. Its sha256 is embedded in the generated TS, and the
    platform's drift test recomputes it.

Usage:
    python3 codegen/generate_policy_types.py [--platform-root PATH] [--check]

`--check` writes nothing and exits 1 if any artifact differs from what would be
generated. That is what CI runs. `--platform-root` defaults to
`../noveum-app-nextjs` relative to the gateway repo root; when it does not exist
the TypeScript artifacts are skipped (and, under `--check`, not verified) so the
gateway's own CI stays hermetic.

Stdlib only, on purpose: this has to run in both repos' CI with no install step.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "schema" / "novaguard-policy.v1.json"
RUST_OUT = REPO_ROOT / "src" / "policy" / "policy_types.generated.rs"

PLATFORM_REL = pathlib.Path("packages/api/src/routes/v1/guardrails/generated")
TS_NAME = "policy-types.generated.ts"
VENDORED_SCHEMA_NAME = "novaguard-policy.v1.json"

GENERATOR_REL = "codegen/generate_policy_types.py"
SCHEMA_REL = "schema/novaguard-policy.v1.json"

ENGINE_KINDS = {
    "live_state": "LiveState",
    "text_rule": "TextRule",
    "external_scorer": "ExternalScorer",
}


def banner(comment: str) -> str:
    return "\n".join(
        [
            f"{comment} @generated by {GENERATOR_REL} from {SCHEMA_REL}",
            f"{comment} DO NOT EDIT THIS FILE BY HAND.",
            f"{comment}",
            f"{comment} Add or change a policy type in {SCHEMA_REL}, then re-run:",
            f"{comment}     python3 {GENERATOR_REL}",
            f"{comment} CI fails if this file and the schema disagree.",
        ]
    )


def load_schema() -> tuple[dict, str, str]:
    raw = SCHEMA_PATH.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    return json.loads(raw), raw.decode("utf-8"), sha


def policy_types(schema: dict) -> list[tuple[str, dict]]:
    """The registry, in declaration order (insertion order is meaningful)."""
    return list(schema["x-policy-types"].items())


def check_internal_consistency(schema: dict) -> list[str]:
    """The schema has to agree with itself before anything is generated."""
    problems: list[str] = []
    registry = schema["x-policy-types"]
    declared = list(registry)
    enum_members = schema["$defs"]["policyType"]["enum"]
    if declared != enum_members:
        problems.append(
            "x-policy-types keys and $defs.policyType.enum disagree:\n"
            f"  registry: {declared}\n"
            f"  enum:     {enum_members}"
        )

    one_of = schema["$defs"]["policy"]["allOf"][1]["oneOf"]
    arm_types = [arm["properties"]["type"]["const"] for arm in one_of]
    if declared != arm_types:
        problems.append(
            "x-policy-types keys and the $defs.policy oneOf arms disagree:\n"
            f"  registry: {declared}\n"
            f"  arms:     {arm_types}"
        )

    for arm in one_of:
        name = arm["properties"]["type"]["const"]
        ref = arm["properties"]["config"]["$ref"]
        expected = f"#/$defs/{registry[name]['configRef']}"
        if ref != expected:
            problems.append(
                f"policy type '{name}': oneOf arm points at {ref} "
                f"but the registry declares configRef {expected}"
            )

    for name, meta in registry.items():
        if meta["configRef"] not in schema["$defs"]:
            problems.append(
                f"policy type '{name}': configRef '{meta['configRef']}' is not in $defs"
            )
        if meta["enforcement"] not in ("enforced", "reserved"):
            problems.append(
                f"policy type '{name}': enforcement must be enforced|reserved, "
                f"got {meta['enforcement']!r}"
            )
        if meta["engine"] not in ENGINE_KINDS:
            problems.append(
                f"policy type '{name}': engine must be one of "
                f"{sorted(ENGINE_KINDS)}, got {meta['engine']!r}"
            )
        if (meta["engine"] == "external_scorer") != (meta["enforcement"] == "reserved"):
            problems.append(
                f"policy type '{name}': external_scorer types are exactly the "
                "reserved ones; enforcement and engine disagree"
            )
        if meta["platformEnum"] != name.upper():
            problems.append(
                f"policy type '{name}': platformEnum {meta['platformEnum']!r} is not "
                f"the SCREAMING_SNAKE spelling of the wire name"
            )
    return problems


def rust_str(value: str) -> str:
    return json.dumps(value)


def render_rust(schema: dict, sha: str) -> str:
    types = policy_types(schema)
    version = schema["x-schema-version"]
    lines: list[str] = [banner("//"), ""]

    lines += [
        "/// The version of `schema/novaguard-policy.v1.json` these types were",
        "/// generated from. A bundle declaring a different MAJOR version must be",
        "/// refused rather than parsed on a best-effort basis.",
        f'pub const POLICY_SCHEMA_VERSION: &str = "{version}";',
        "",
        "/// sha256 of the schema file, so a hand-edited copy elsewhere is detectable.",
        f'pub const POLICY_SCHEMA_SHA256: &str = "{sha}";',
        "",
        "/// The schema document itself, embedded so validation needs no filesystem",
        "/// access (the Cloudflare Worker target has none).",
        "pub const POLICY_SCHEMA_JSON: &str =",
        f'    include_str!("{"../../schema/novaguard-policy.v1.json"}");',
        "",
        "/// Which subsystem evaluates a policy type.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]",
        "pub enum PolicyEngineKind {",
        "    /// Evaluated by the engine against cross-request cost/rate counters.",
        "    LiveState,",
        "    /// Evaluated in-process by a `PolicyRule` over the payload text.",
        "    TextRule,",
        "    /// Requires an external scoring service the gateway does not call.",
        "    /// Parsed and validated, but never enforced by this build.",
        "    ExternalScorer,",
        "    /// Not a policy type this build knows about at all.",
        "    Unsupported,",
        "}",
        "",
        "/// Every policy type in the NovaGuard contract.",
        "///",
        "/// `Unknown` is not a contract member: it is the catch-all for a `type`",
        "/// string this build does not recognize. It is deliberately NOT silently",
        "/// skipped by the engine — see `PolicyEngine::compile`.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]",
        "pub enum PolicyType {",
    ]

    for name, meta in types:
        lines.append(f"    /// `{name}` — {meta['title']}.")
        lines.append(f"    #[serde(rename = {rust_str(name)})]")
        lines.append(f"    {meta['rustVariant']},")
    lines += [
        "    /// A `type` string absent from the schema. Always a hard error.",
        "    #[serde(other)]",
        "    Unknown,",
        "}",
        "",
        "impl PolicyType {",
        "    /// Every type in the contract, in schema declaration order.",
        f"    pub const ALL: [PolicyType; {len(types)}] = [",
    ]
    for _, meta in types:
        lines.append(f"        PolicyType::{meta['rustVariant']},")
    lines += [
        "    ];",
        "",
        "    /// The canonical snake_case wire spelling.",
        "    pub fn as_str(self) -> &'static str {",
        "        match self {",
    ]
    for name, meta in types:
        lines.append(f"            PolicyType::{meta['rustVariant']} => {rust_str(name)},")
    lines += [
        '            PolicyType::Unknown => "unknown",',
        "        }",
        "    }",
        "",
        "    /// The platform's SCREAMING_SNAKE spelling (also the Prisma enum member).",
        "    pub fn platform_enum(self) -> &'static str {",
        "        match self {",
    ]
    for _, meta in types:
        lines.append(
            f"            PolicyType::{meta['rustVariant']} => {rust_str(meta['platformEnum'])},"
        )
    lines += [
        '            PolicyType::Unknown => "UNKNOWN",',
        "        }",
        "    }",
        "",
        "    /// Parse a wire spelling. Unrecognized input yields `Unknown`, which the",
        "    /// engine turns into a visible rejection rather than a silent skip.",
        "    pub fn from_wire(s: &str) -> PolicyType {",
        "        match s {",
    ]
    for name, meta in types:
        lines.append(f"            {rust_str(name)} => PolicyType::{meta['rustVariant']},")
    lines += [
        "            _ => PolicyType::Unknown,",
        "        }",
        "    }",
        "",
        "    /// Parse a platform SCREAMING_SNAKE spelling (case-insensitively).",
        "    pub fn from_platform_enum(s: &str) -> PolicyType {",
        "        PolicyType::from_wire(s.trim().to_ascii_lowercase().as_str())",
        "    }",
        "",
        "    /// Which subsystem evaluates this type.",
        "    pub fn engine_kind(self) -> PolicyEngineKind {",
        "        match self {",
    ]
    for _, meta in types:
        lines.append(
            f"            PolicyType::{meta['rustVariant']} => "
            f"PolicyEngineKind::{ENGINE_KINDS[meta['engine']]},"
        )
    lines += [
        "            PolicyType::Unknown => PolicyEngineKind::Unsupported,",
        "        }",
        "    }",
        "",
        "    /// Does this build actually enforce the type? `false` for the reserved",
        "    /// classifier types and for `Unknown`.",
        "    pub fn is_enforced(self) -> bool {",
        "        matches!(",
        "            self.engine_kind(),",
        "            PolicyEngineKind::LiveState | PolicyEngineKind::TextRule",
        "        )",
        "    }",
        "",
        "    /// Enforced entirely in-process, with no network dependency.",
        "    pub fn is_deterministic(self) -> bool {",
        "        self.is_enforced()",
        "    }",
        "",
        "    /// The `$defs` key of this type's config schema, for validation.",
        "    pub fn config_def(self) -> Option<&'static str> {",
        "        match self {",
    ]
    for _, meta in types:
        lines.append(
            f"            PolicyType::{meta['rustVariant']} => Some({rust_str(meta['configRef'])}),"
        )
    lines += [
        "            PolicyType::Unknown => None,",
        "        }",
        "    }",
        "",
        "    /// Human-readable title, for operator-facing errors.",
        "    pub fn title(self) -> &'static str {",
        "        match self {",
    ]
    for _, meta in types:
        lines.append(
            f"            PolicyType::{meta['rustVariant']} => {rust_str(meta['title'])},"
        )
    lines += [
        '            PolicyType::Unknown => "Unknown policy type",',
        "        }",
        "    }",
        "}",
        "",
        "/// Every wire spelling in the contract, comma-separated. Used to make an",
        "/// unknown-type rejection actionable.",
        f"pub const POLICY_TYPE_NAMES: [&str; {len(types)}] = [",
    ]
    for name, _ in types:
        lines.append(f"    {rust_str(name)},")
    lines += ["];", ""]

    return "\n".join(lines)


def ts_str(value: str) -> str:
    return json.dumps(value)


def render_ts(schema: dict, sha: str) -> str:
    types = policy_types(schema)
    version = schema["x-schema-version"]
    fail_closed = schema["$defs"]["policyBase"]["properties"]["failClosed"]
    lines: list[str] = [banner("//"), ""]

    lines += [
        "/**",
        " * The NovaGuard policy contract, derived from the versioned JSON Schema.",
        " *",
        " * `schemas.ts` builds its Zod schemas on top of these constants, and",
        " * `schemas.drift.test.ts` asserts the Zod shapes still match the vendored",
        " * schema next to this file.",
        " */",
        "",
        f"export const POLICY_SCHEMA_VERSION = {ts_str(version)} as const;",
        "",
        "/** sha256 of schema/novaguard-policy.v1.json in the ai-gateway repo. */",
        f"export const POLICY_SCHEMA_SHA256 = {ts_str(sha)} as const;",
        "",
        "/** Wire (snake_case) spellings, in schema declaration order. */",
        "export const POLICY_TYPE_WIRE_NAMES = [",
    ]
    for name, _ in types:
        lines.append(f"  {ts_str(name)},")
    lines += [
        "] as const;",
        "",
        "/**",
        " * SCREAMING_SNAKE spellings. This is the platform's own vocabulary AND the",
        " * exact member list the Prisma `PolicyType` enum must carry.",
        " */",
        "export const POLICY_TYPE_NAMES = [",
    ]
    for _, meta in types:
        lines.append(f"  {ts_str(meta['platformEnum'])},")
    lines += [
        "] as const;",
        "",
        "export type PolicyTypeName = (typeof POLICY_TYPE_NAMES)[number];",
        "export type PolicyTypeWireName = (typeof POLICY_TYPE_WIRE_NAMES)[number];",
        "",
        "export type PolicyEnforcement = 'enforced' | 'reserved';",
        "export type PolicyEngineKind =",
        "  | 'live_state'",
        "  | 'text_rule'",
        "  | 'external_scorer';",
        "",
        "export interface PolicyTypeMeta {",
        "  readonly wireName: PolicyTypeWireName;",
        "  readonly title: string;",
        "  readonly description: string;",
        "  /**",
        "   * `reserved` types are accepted and stored, but the gateway cannot act on",
        "   * them without an external scoring service. Surface that in the UI rather",
        "   * than letting an operator believe the policy is live.",
        "   */",
        "  readonly enforcement: PolicyEnforcement;",
        "  readonly engine: PolicyEngineKind;",
        "  readonly phases: readonly string[];",
        "  /** Key under `$defs` in the vendored schema holding this type's config. */",
        "  readonly configDef: string;",
        "}",
        "",
        "export const POLICY_TYPE_META: Readonly<",
        "  Record<PolicyTypeName, PolicyTypeMeta>",
        "> = {",
    ]
    for name, meta in types:
        lines += [
            f"  {meta['platformEnum']}: {{",
            f"    wireName: {ts_str(name)},",
            f"    title: {ts_str(meta['title'])},",
            f"    description: {ts_str(meta['description'])},",
            f"    enforcement: {ts_str(meta['enforcement'])},",
            f"    engine: {ts_str(meta['engine'])},",
            f"    phases: [{', '.join(ts_str(p) for p in meta['phases'])}],",
            f"    configDef: {ts_str(meta['configRef'])},",
            "  },",
        ]
    lines += [
        "};",
        "",
        "/** Types the gateway actually enforces today. */",
        "export const ENFORCED_POLICY_TYPES = [",
    ]
    for _, meta in types:
        if meta["enforcement"] == "enforced":
            lines.append(f"  {ts_str(meta['platformEnum'])},")
    lines += [
        "] as const;",
        "",
        "/** Types accepted and stored but not enforced by any gateway build yet. */",
        "export const RESERVED_POLICY_TYPES = [",
    ]
    for _, meta in types:
        if meta["enforcement"] == "reserved":
            lines.append(f"  {ts_str(meta['platformEnum'])},")
    lines += [
        "] as const;",
        "",
        "/**",
        " * The value the create/update API fills in when the client omits",
        " * `failClosed`. Deliberately different from the schema's wire default",
        " * (`false`): a stored row is always explicit, a hand-written bundle is not.",
        " */",
        f"export const FAIL_CLOSED_CREATE_DEFAULT = {json.dumps(fail_closed['x-platform-create-default'])} as const;",
        "",
        "/** The wire default, for bundles exported to the gateway. */",
        f"export const FAIL_CLOSED_WIRE_DEFAULT = {json.dumps(fail_closed['default'])} as const;",
        "",
    ]
    return "\n".join(lines)


def write_or_check(path: pathlib.Path, content: str, check: bool) -> list[str]:
    rel = path
    try:
        rel = path.relative_to(REPO_ROOT)
    except ValueError:
        pass
    if check:
        if not path.exists():
            return [f"MISSING  {rel} (run: python3 {GENERATOR_REL})"]
        current = path.read_text(encoding="utf-8")
        if current != content:
            return [f"DRIFTED  {rel} (run: python3 {GENERATOR_REL})"]
        return []
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return []
    path.write_text(content, encoding="utf-8")
    print(f"wrote    {rel}")
    return []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--platform-root",
        default=str(REPO_ROOT.parent / "noveum-app-nextjs"),
        help="path to the noveum-app-nextjs checkout (skipped when absent)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if any artifact is out of date",
    )
    args = parser.parse_args()

    schema, schema_text, sha = load_schema()

    problems = check_internal_consistency(schema)
    if problems:
        print("schema is internally inconsistent:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    failures = write_or_check(RUST_OUT, render_rust(schema, sha), args.check)

    platform_root = pathlib.Path(args.platform_root).expanduser()
    gen_dir = platform_root / PLATFORM_REL
    if platform_root.is_dir():
        failures += write_or_check(gen_dir / TS_NAME, render_ts(schema, sha), args.check)
        failures += write_or_check(
            gen_dir / VENDORED_SCHEMA_NAME, schema_text, args.check
        )
    else:
        print(
            f"note: platform root {platform_root} not found; "
            "skipping the TypeScript artifacts",
            file=sys.stderr,
        )

    if failures:
        print("\npolicy-type codegen is out of date:", file=sys.stderr)
        for f in failures:
            print(f"  {f}", file=sys.stderr)
        return 1

    if args.check:
        print("policy-type codegen is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
