// @generated by codegen/generate_policy_types.py from schema/novaguard-policy.v1.json
// DO NOT EDIT THIS FILE BY HAND.
//
// Add or change a policy type in schema/novaguard-policy.v1.json, then re-run:
//     python3 codegen/generate_policy_types.py
// CI fails if this file and the schema disagree.

/// The version of `schema/novaguard-policy.v1.json` these types were
/// generated from. A bundle declaring a different MAJOR version must be
/// refused rather than parsed on a best-effort basis.
pub const POLICY_SCHEMA_VERSION: &str = "1.0.0";

/// sha256 of the schema file, so a hand-edited copy elsewhere is detectable.
pub const POLICY_SCHEMA_SHA256: &str = "a30c1b900ef0be757afc7d4f7aeafb857b7fa3399dada55eb23e334c4177b349";

/// The schema document itself, embedded so validation needs no filesystem
/// access (the Cloudflare Worker target has none).
pub const POLICY_SCHEMA_JSON: &str =
    include_str!("../../schema/novaguard-policy.v1.json");

/// Which subsystem evaluates a policy type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PolicyEngineKind {
    /// Evaluated by the engine against cross-request cost/rate counters.
    LiveState,
    /// Evaluated in-process by a `PolicyRule` over the payload text.
    TextRule,
    /// Requires an external scoring service the gateway does not call.
    /// Parsed and validated, but never enforced by this build.
    ExternalScorer,
    /// Not a policy type this build knows about at all.
    Unsupported,
}

/// Every policy type in the NovaGuard contract.
///
/// `Unknown` is not a contract member: it is the catch-all for a `type`
/// string this build does not recognize. It is deliberately NOT silently
/// skipped by the engine — see `PolicyEngine::compile`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum PolicyType {
    /// `cost_cap` — Cost cap.
    #[serde(rename = "cost_cap")]
    CostCap,
    /// `rate_limit` — Rate limit.
    #[serde(rename = "rate_limit")]
    RateLimit,
    /// `model_allowlist` — Model allow/deny list.
    #[serde(rename = "model_allowlist")]
    ModelAllowlist,
    /// `regex_match` — Regex match.
    #[serde(rename = "regex_match")]
    RegexMatch,
    /// `banned_substrings` — Banned substrings.
    #[serde(rename = "banned_substrings")]
    BannedSubstrings,
    /// `pii_detection` — PII detection.
    #[serde(rename = "pii_detection")]
    PiiDetection,
    /// `secrets_detection` — Secrets detection.
    #[serde(rename = "secrets_detection")]
    SecretsDetection,
    /// `json_schema` — JSON schema conformance.
    #[serde(rename = "json_schema")]
    JsonSchema,
    /// `token_length_cap` — Token length cap.
    #[serde(rename = "token_length_cap")]
    TokenLengthCap,
    /// `scorer_gate` — Scorer gate.
    #[serde(rename = "scorer_gate")]
    ScorerGate,
    /// `prompt_injection` — Prompt injection detection.
    #[serde(rename = "prompt_injection")]
    PromptInjection,
    /// `topic_restriction` — Topic restriction.
    #[serde(rename = "topic_restriction")]
    TopicRestriction,
    /// `content_moderation` — Content moderation.
    #[serde(rename = "content_moderation")]
    ContentModeration,
    /// `grounding_check` — Grounding check.
    #[serde(rename = "grounding_check")]
    GroundingCheck,
    /// A `type` string absent from the schema. Always a hard error.
    #[serde(other)]
    Unknown,
}

impl PolicyType {
    /// Every type in the contract, in schema declaration order.
    pub const ALL: [PolicyType; 14] = [
        PolicyType::CostCap,
        PolicyType::RateLimit,
        PolicyType::ModelAllowlist,
        PolicyType::RegexMatch,
        PolicyType::BannedSubstrings,
        PolicyType::PiiDetection,
        PolicyType::SecretsDetection,
        PolicyType::JsonSchema,
        PolicyType::TokenLengthCap,
        PolicyType::ScorerGate,
        PolicyType::PromptInjection,
        PolicyType::TopicRestriction,
        PolicyType::ContentModeration,
        PolicyType::GroundingCheck,
    ];

    /// The canonical snake_case wire spelling.
    pub fn as_str(self) -> &'static str {
        match self {
            PolicyType::CostCap => "cost_cap",
            PolicyType::RateLimit => "rate_limit",
            PolicyType::ModelAllowlist => "model_allowlist",
            PolicyType::RegexMatch => "regex_match",
            PolicyType::BannedSubstrings => "banned_substrings",
            PolicyType::PiiDetection => "pii_detection",
            PolicyType::SecretsDetection => "secrets_detection",
            PolicyType::JsonSchema => "json_schema",
            PolicyType::TokenLengthCap => "token_length_cap",
            PolicyType::ScorerGate => "scorer_gate",
            PolicyType::PromptInjection => "prompt_injection",
            PolicyType::TopicRestriction => "topic_restriction",
            PolicyType::ContentModeration => "content_moderation",
            PolicyType::GroundingCheck => "grounding_check",
            PolicyType::Unknown => "unknown",
        }
    }

    /// The platform's SCREAMING_SNAKE spelling (also the Prisma enum member).
    pub fn platform_enum(self) -> &'static str {
        match self {
            PolicyType::CostCap => "COST_CAP",
            PolicyType::RateLimit => "RATE_LIMIT",
            PolicyType::ModelAllowlist => "MODEL_ALLOWLIST",
            PolicyType::RegexMatch => "REGEX_MATCH",
            PolicyType::BannedSubstrings => "BANNED_SUBSTRINGS",
            PolicyType::PiiDetection => "PII_DETECTION",
            PolicyType::SecretsDetection => "SECRETS_DETECTION",
            PolicyType::JsonSchema => "JSON_SCHEMA",
            PolicyType::TokenLengthCap => "TOKEN_LENGTH_CAP",
            PolicyType::ScorerGate => "SCORER_GATE",
            PolicyType::PromptInjection => "PROMPT_INJECTION",
            PolicyType::TopicRestriction => "TOPIC_RESTRICTION",
            PolicyType::ContentModeration => "CONTENT_MODERATION",
            PolicyType::GroundingCheck => "GROUNDING_CHECK",
            PolicyType::Unknown => "UNKNOWN",
        }
    }

    /// Parse a wire spelling. Unrecognized input yields `Unknown`, which the
    /// engine turns into a visible rejection rather than a silent skip.
    pub fn from_wire(s: &str) -> PolicyType {
        match s {
            "cost_cap" => PolicyType::CostCap,
            "rate_limit" => PolicyType::RateLimit,
            "model_allowlist" => PolicyType::ModelAllowlist,
            "regex_match" => PolicyType::RegexMatch,
            "banned_substrings" => PolicyType::BannedSubstrings,
            "pii_detection" => PolicyType::PiiDetection,
            "secrets_detection" => PolicyType::SecretsDetection,
            "json_schema" => PolicyType::JsonSchema,
            "token_length_cap" => PolicyType::TokenLengthCap,
            "scorer_gate" => PolicyType::ScorerGate,
            "prompt_injection" => PolicyType::PromptInjection,
            "topic_restriction" => PolicyType::TopicRestriction,
            "content_moderation" => PolicyType::ContentModeration,
            "grounding_check" => PolicyType::GroundingCheck,
            _ => PolicyType::Unknown,
        }
    }

    /// Parse a platform SCREAMING_SNAKE spelling (case-insensitively).
    pub fn from_platform_enum(s: &str) -> PolicyType {
        PolicyType::from_wire(s.trim().to_ascii_lowercase().as_str())
    }

    /// Which subsystem evaluates this type.
    pub fn engine_kind(self) -> PolicyEngineKind {
        match self {
            PolicyType::CostCap => PolicyEngineKind::LiveState,
            PolicyType::RateLimit => PolicyEngineKind::LiveState,
            PolicyType::ModelAllowlist => PolicyEngineKind::TextRule,
            PolicyType::RegexMatch => PolicyEngineKind::TextRule,
            PolicyType::BannedSubstrings => PolicyEngineKind::TextRule,
            PolicyType::PiiDetection => PolicyEngineKind::TextRule,
            PolicyType::SecretsDetection => PolicyEngineKind::TextRule,
            PolicyType::JsonSchema => PolicyEngineKind::TextRule,
            PolicyType::TokenLengthCap => PolicyEngineKind::TextRule,
            PolicyType::ScorerGate => PolicyEngineKind::ExternalScorer,
            PolicyType::PromptInjection => PolicyEngineKind::ExternalScorer,
            PolicyType::TopicRestriction => PolicyEngineKind::ExternalScorer,
            PolicyType::ContentModeration => PolicyEngineKind::ExternalScorer,
            PolicyType::GroundingCheck => PolicyEngineKind::ExternalScorer,
            PolicyType::Unknown => PolicyEngineKind::Unsupported,
        }
    }

    /// Does this build actually enforce the type? `false` for the reserved
    /// classifier types and for `Unknown`.
    pub fn is_enforced(self) -> bool {
        matches!(
            self.engine_kind(),
            PolicyEngineKind::LiveState | PolicyEngineKind::TextRule
        )
    }

    /// Enforced entirely in-process, with no network dependency.
    pub fn is_deterministic(self) -> bool {
        self.is_enforced()
    }

    /// The `$defs` key of this type's config schema, for validation.
    pub fn config_def(self) -> Option<&'static str> {
        match self {
            PolicyType::CostCap => Some("costCapConfig"),
            PolicyType::RateLimit => Some("rateLimitConfig"),
            PolicyType::ModelAllowlist => Some("modelAllowlistConfig"),
            PolicyType::RegexMatch => Some("regexMatchConfig"),
            PolicyType::BannedSubstrings => Some("bannedSubstringsConfig"),
            PolicyType::PiiDetection => Some("piiDetectionConfig"),
            PolicyType::SecretsDetection => Some("secretsDetectionConfig"),
            PolicyType::JsonSchema => Some("jsonSchemaConfig"),
            PolicyType::TokenLengthCap => Some("tokenLengthCapConfig"),
            PolicyType::ScorerGate => Some("scorerGateConfig"),
            PolicyType::PromptInjection => Some("promptInjectionConfig"),
            PolicyType::TopicRestriction => Some("topicRestrictionConfig"),
            PolicyType::ContentModeration => Some("contentModerationConfig"),
            PolicyType::GroundingCheck => Some("groundingCheckConfig"),
            PolicyType::Unknown => None,
        }
    }

    /// Human-readable title, for operator-facing errors.
    pub fn title(self) -> &'static str {
        match self {
            PolicyType::CostCap => "Cost cap",
            PolicyType::RateLimit => "Rate limit",
            PolicyType::ModelAllowlist => "Model allow/deny list",
            PolicyType::RegexMatch => "Regex match",
            PolicyType::BannedSubstrings => "Banned substrings",
            PolicyType::PiiDetection => "PII detection",
            PolicyType::SecretsDetection => "Secrets detection",
            PolicyType::JsonSchema => "JSON schema conformance",
            PolicyType::TokenLengthCap => "Token length cap",
            PolicyType::ScorerGate => "Scorer gate",
            PolicyType::PromptInjection => "Prompt injection detection",
            PolicyType::TopicRestriction => "Topic restriction",
            PolicyType::ContentModeration => "Content moderation",
            PolicyType::GroundingCheck => "Grounding check",
            PolicyType::Unknown => "Unknown policy type",
        }
    }
}

/// Every wire spelling in the contract, comma-separated. Used to make an
/// unknown-type rejection actionable.
pub const POLICY_TYPE_NAMES: [&str; 14] = [
    "cost_cap",
    "rate_limit",
    "model_allowlist",
    "regex_match",
    "banned_substrings",
    "pii_detection",
    "secrets_detection",
    "json_schema",
    "token_length_cap",
    "scorer_gate",
    "prompt_injection",
    "topic_restriction",
    "content_moderation",
    "grounding_check",
];
