//! Hand-maintained. The platform's
//! `packages/telemetry/src/pricing/generated/index.ts` holds the same rates and
//! must be updated alongside any change here.
//!
//! Published LLM rates.
//!
//! Every rate is USD per 1,000,000 tokens. `cached_input_per_1m` prices a
//! prompt-cache HIT and `cache_write_per_1m` prices tokens written INTO the
//! cache; `None` means the provider publishes no rate for that dimension, so
//! [`crate::policy::pricing`] reports it as a missing dimension instead of
//! charging zero for it. `Some(0.0)` is different: it means the provider
//! documents that the dimension is genuinely free.
//!
//! Rows are limited to models the gateway can actually route to. The catalog
//! also carries the platform's historical rows; those belong only in the
//! TypeScript table (see `targets` in the catalog).

/// The rate card these rows came from. Recorded on every usage and
/// reservation record so a billed amount can be traced back to it.
pub const CATALOG_VERSION: &str = "2026.08.12";

/// One model's published rates.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CatalogRow {
    pub id: &'static str,
    pub provider: &'static str,
    pub input_per_1m: f64,
    pub output_per_1m: f64,
    /// Prompt-cache HIT rate. `None` when the provider publishes none.
    pub cached_input_per_1m: Option<f64>,
    /// Cache-write rate at the provider's default TTL. `Some(0.0)` means
    /// documented-free; `None` means unpublished.
    pub cache_write_per_1m: Option<f64>,
    /// Anthropic's 1-hour-TTL cache write (2x base). `None` when the
    /// provider has a single write rate.
    pub cache_write_1h_per_1m: Option<f64>,
}

/// 65 models the gateway prices from the catalog.
pub const MODEL_ROWS: &[CatalogRow] = &[
    CatalogRow {
        id: "gpt-5.6-luna",
        provider: "openai",
        input_per_1m: 0.2,
        output_per_1m: 1.2,
        cached_input_per_1m: Some(0.02),
        cache_write_per_1m: Some(0.25),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-5.6-terra",
        provider: "openai",
        input_per_1m: 2.0,
        output_per_1m: 12.0,
        cached_input_per_1m: Some(0.2),
        cache_write_per_1m: Some(2.5),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-5.6-sol",
        provider: "openai",
        input_per_1m: 5.0,
        output_per_1m: 30.0,
        cached_input_per_1m: Some(0.5),
        cache_write_per_1m: Some(6.25),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-5",
        provider: "openai",
        input_per_1m: 1.25,
        output_per_1m: 10.0,
        cached_input_per_1m: Some(0.125),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-5-mini",
        provider: "openai",
        input_per_1m: 0.25,
        output_per_1m: 2.0,
        cached_input_per_1m: Some(0.025),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-5-nano",
        provider: "openai",
        input_per_1m: 0.05,
        output_per_1m: 0.4,
        cached_input_per_1m: Some(0.005),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-4.1",
        provider: "openai",
        input_per_1m: 2.0,
        output_per_1m: 8.0,
        cached_input_per_1m: Some(0.5),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-4.1-mini",
        provider: "openai",
        input_per_1m: 0.4,
        output_per_1m: 1.6,
        cached_input_per_1m: Some(0.1),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-4.1-nano",
        provider: "openai",
        input_per_1m: 0.1,
        output_per_1m: 0.4,
        cached_input_per_1m: Some(0.025),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-4o",
        provider: "openai",
        input_per_1m: 2.5,
        output_per_1m: 10.0,
        cached_input_per_1m: Some(1.25),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gpt-4o-mini",
        provider: "openai",
        input_per_1m: 0.15,
        output_per_1m: 0.6,
        cached_input_per_1m: Some(0.075),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "o3",
        provider: "openai",
        input_per_1m: 2.0,
        output_per_1m: 8.0,
        cached_input_per_1m: Some(0.5),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "o4-mini",
        provider: "openai",
        input_per_1m: 1.1,
        output_per_1m: 4.4,
        cached_input_per_1m: Some(0.275),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "o1",
        provider: "openai",
        input_per_1m: 15.0,
        output_per_1m: 60.0,
        cached_input_per_1m: None,
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "text-embedding-3-small",
        provider: "openai",
        input_per_1m: 0.02,
        output_per_1m: 0.0,
        cached_input_per_1m: None,
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "text-embedding-3-large",
        provider: "openai",
        input_per_1m: 0.13,
        output_per_1m: 0.0,
        cached_input_per_1m: None,
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "claude-sonnet-5",
        provider: "anthropic",
        input_per_1m: 2.0,
        output_per_1m: 10.0,
        cached_input_per_1m: Some(0.2),
        cache_write_per_1m: Some(2.5),
        cache_write_1h_per_1m: Some(4.0),
    },
    CatalogRow {
        id: "claude-opus-4-8",
        provider: "anthropic",
        input_per_1m: 5.0,
        output_per_1m: 25.0,
        cached_input_per_1m: Some(0.5),
        cache_write_per_1m: Some(6.25),
        cache_write_1h_per_1m: Some(10.0),
    },
    CatalogRow {
        id: "claude-opus-4-7",
        provider: "anthropic",
        input_per_1m: 5.0,
        output_per_1m: 25.0,
        cached_input_per_1m: Some(0.5),
        cache_write_per_1m: Some(6.25),
        cache_write_1h_per_1m: Some(10.0),
    },
    CatalogRow {
        id: "claude-opus-4-6",
        provider: "anthropic",
        input_per_1m: 5.0,
        output_per_1m: 25.0,
        cached_input_per_1m: Some(0.5),
        cache_write_per_1m: Some(6.25),
        cache_write_1h_per_1m: Some(10.0),
    },
    CatalogRow {
        id: "claude-sonnet-4-6",
        provider: "anthropic",
        input_per_1m: 3.0,
        output_per_1m: 15.0,
        cached_input_per_1m: Some(0.3),
        cache_write_per_1m: Some(3.75),
        cache_write_1h_per_1m: Some(6.0),
    },
    CatalogRow {
        id: "claude-sonnet-4-5",
        provider: "anthropic",
        input_per_1m: 3.0,
        output_per_1m: 15.0,
        cached_input_per_1m: Some(0.3),
        cache_write_per_1m: Some(3.75),
        cache_write_1h_per_1m: Some(6.0),
    },
    CatalogRow {
        id: "claude-haiku-4-5",
        provider: "anthropic",
        input_per_1m: 1.0,
        output_per_1m: 5.0,
        cached_input_per_1m: Some(0.1),
        cache_write_per_1m: Some(1.25),
        cache_write_1h_per_1m: Some(2.0),
    },
    CatalogRow {
        id: "claude-fable-5",
        provider: "anthropic",
        input_per_1m: 10.0,
        output_per_1m: 50.0,
        cached_input_per_1m: Some(1.0),
        cache_write_per_1m: Some(12.5),
        cache_write_1h_per_1m: Some(20.0),
    },
    CatalogRow {
        id: "gemini-3.6-flash",
        provider: "google",
        input_per_1m: 1.5,
        output_per_1m: 7.5,
        cached_input_per_1m: Some(0.15),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gemini-2.5-pro",
        provider: "google",
        input_per_1m: 1.25,
        output_per_1m: 10.0,
        cached_input_per_1m: Some(0.125),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gemini-2.5-flash",
        provider: "google",
        input_per_1m: 0.3,
        output_per_1m: 2.5,
        cached_input_per_1m: Some(0.03),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "gemini-2.5-flash-lite",
        provider: "google",
        input_per_1m: 0.1,
        output_per_1m: 0.4,
        cached_input_per_1m: Some(0.01),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "llama-3.3-70b-versatile",
        provider: "groq",
        input_per_1m: 0.59,
        output_per_1m: 0.79,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "llama-3.1-8b-instant",
        provider: "groq",
        input_per_1m: 0.05,
        output_per_1m: 0.08,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "meta-llama/llama-4-scout-17b-16e-instruct",
        provider: "groq",
        input_per_1m: 0.11,
        output_per_1m: 0.34,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "openai/gpt-oss-120b",
        provider: "groq",
        input_per_1m: 0.15,
        output_per_1m: 0.6,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "openai/gpt-oss-20b",
        provider: "groq",
        input_per_1m: 0.075,
        output_per_1m: 0.3,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "mistral-large-latest",
        provider: "mistral",
        input_per_1m: 0.5,
        output_per_1m: 1.5,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "mistral-medium-latest",
        provider: "mistral",
        input_per_1m: 1.5,
        output_per_1m: 7.5,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "mistral-small-latest",
        provider: "mistral",
        input_per_1m: 0.15,
        output_per_1m: 0.6,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "codestral-latest",
        provider: "mistral",
        input_per_1m: 0.3,
        output_per_1m: 0.9,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "magistral-medium-latest",
        provider: "mistral",
        input_per_1m: 2.0,
        output_per_1m: 5.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "command-a-03-2025",
        provider: "cohere",
        input_per_1m: 2.5,
        output_per_1m: 10.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "command-r-plus-08-2024",
        provider: "cohere",
        input_per_1m: 2.5,
        output_per_1m: 10.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "command-r-08-2024",
        provider: "cohere",
        input_per_1m: 0.15,
        output_per_1m: 0.6,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "command-r7b-12-2024",
        provider: "cohere",
        input_per_1m: 0.0375,
        output_per_1m: 0.15,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "meta-llama/llama-3.3-70b-instruct-turbo",
        provider: "together",
        input_per_1m: 1.04,
        output_per_1m: 1.04,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "meta-llama/llama-4-maverick-17b-128e-instruct-fp8",
        provider: "together",
        input_per_1m: 0.27,
        output_per_1m: 0.85,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "deepseek-ai/deepseek-v3",
        provider: "together",
        input_per_1m: 1.25,
        output_per_1m: 1.25,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "accounts/fireworks/models/deepseek-v4-pro",
        provider: "fireworks",
        input_per_1m: 1.74,
        output_per_1m: 3.48,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "accounts/fireworks/models/deepseek-v4-flash",
        provider: "fireworks",
        input_per_1m: 0.14,
        output_per_1m: 0.28,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "accounts/fireworks/models/kimi-k2p6",
        provider: "fireworks",
        input_per_1m: 0.95,
        output_per_1m: 4.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        provider: "fireworks",
        input_per_1m: 0.9,
        output_per_1m: 0.9,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "anthropic.claude-opus-4-5-20251101-v1:0",
        provider: "bedrock",
        input_per_1m: 5.0,
        output_per_1m: 25.0,
        cached_input_per_1m: Some(0.5),
        cache_write_per_1m: Some(6.25),
        cache_write_1h_per_1m: Some(10.0),
    },
    CatalogRow {
        id: "anthropic.claude-sonnet-4-5-20250929-v1:0",
        provider: "bedrock",
        input_per_1m: 3.0,
        output_per_1m: 15.0,
        cached_input_per_1m: Some(0.3),
        cache_write_per_1m: Some(3.75),
        cache_write_1h_per_1m: Some(6.0),
    },
    CatalogRow {
        id: "anthropic.claude-haiku-4-5-20251001-v1:0",
        provider: "bedrock",
        input_per_1m: 1.0,
        output_per_1m: 5.0,
        cached_input_per_1m: Some(0.1),
        cache_write_per_1m: Some(1.25),
        cache_write_1h_per_1m: Some(2.0),
    },
    CatalogRow {
        id: "amazon.nova-pro-v1:0",
        provider: "bedrock",
        input_per_1m: 0.8,
        output_per_1m: 3.2,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "amazon.nova-lite-v1:0",
        provider: "bedrock",
        input_per_1m: 0.06,
        output_per_1m: 0.24,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "amazon.nova-micro-v1:0",
        provider: "bedrock",
        input_per_1m: 0.035,
        output_per_1m: 0.14,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "amazon.nova-premier-v1:0",
        provider: "bedrock",
        input_per_1m: 2.5,
        output_per_1m: 12.5,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "deepseek-v4-flash",
        provider: "deepseek",
        input_per_1m: 0.14,
        output_per_1m: 0.28,
        cached_input_per_1m: Some(0.0028),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "deepseek-v4-pro",
        provider: "deepseek",
        input_per_1m: 0.435,
        output_per_1m: 0.87,
        cached_input_per_1m: Some(0.003625),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "deepseek-chat",
        provider: "deepseek",
        input_per_1m: 0.27,
        output_per_1m: 1.1,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "deepseek-reasoner",
        provider: "deepseek",
        input_per_1m: 0.55,
        output_per_1m: 2.19,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "grok-4.3",
        provider: "xai",
        input_per_1m: 1.25,
        output_per_1m: 2.5,
        cached_input_per_1m: Some(0.2),
        cache_write_per_1m: Some(0.0),
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "grok-build-0.1",
        provider: "xai",
        input_per_1m: 1.0,
        output_per_1m: 2.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "sonar",
        provider: "perplexity",
        input_per_1m: 1.0,
        output_per_1m: 1.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "sonar-pro",
        provider: "perplexity",
        input_per_1m: 3.0,
        output_per_1m: 15.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
    CatalogRow {
        id: "sonar-reasoning-pro",
        provider: "perplexity",
        input_per_1m: 2.0,
        output_per_1m: 8.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
        cache_write_1h_per_1m: None,
    },
];

/// Bare provider aliases resolved server-side, `(alias, concrete_id)`.
pub const MODEL_ALIASES: &[(&str, &str)] = &[("gpt-5.6", "gpt-5.6-sol")];

/// A documented long-context tier: above `threshold_input_tokens` the WHOLE
/// request bills at these rates instead of the model's base row.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LongContextRow {
    pub id: &'static str,
    pub threshold_input_tokens: u32,
    pub input_per_1m: f64,
    pub output_per_1m: f64,
    pub cached_input_per_1m: Option<f64>,
    pub cache_write_per_1m: Option<f64>,
}

pub const LONG_CONTEXT_ROWS: &[LongContextRow] = &[
    LongContextRow {
        id: "gpt-5.6-luna",
        threshold_input_tokens: 272000,
        input_per_1m: 0.4,
        output_per_1m: 1.8,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
    },
    LongContextRow {
        id: "gpt-5.6-terra",
        threshold_input_tokens: 272000,
        input_per_1m: 4.0,
        output_per_1m: 18.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
    },
    LongContextRow {
        id: "gpt-5.6-sol",
        threshold_input_tokens: 272000,
        input_per_1m: 10.0,
        output_per_1m: 45.0,
        cached_input_per_1m: None,
        cache_write_per_1m: None,
    },
    LongContextRow {
        id: "gemini-2.5-pro",
        threshold_input_tokens: 200000,
        input_per_1m: 2.5,
        output_per_1m: 15.0,
        cached_input_per_1m: Some(0.25),
        cache_write_per_1m: Some(0.0),
    },
    LongContextRow {
        id: "grok-4.3",
        threshold_input_tokens: 200000,
        input_per_1m: 2.5,
        output_per_1m: 5.0,
        cached_input_per_1m: Some(0.4),
        cache_write_per_1m: Some(0.0),
    },
];

/// An announced, already-published future price change. The latest entry
/// whose `effective_from_unix_secs` has passed replaces the base row.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ScheduledRow {
    pub id: &'static str,
    pub effective_from_unix_secs: i64,
    pub input_per_1m: f64,
    pub output_per_1m: f64,
}

pub const SCHEDULED_ROWS: &[ScheduledRow] = &[];

/// Per-request tool and search fees, `(tool_id, usd_per_1000_calls)`. Tool
/// ids are `provider:tool` or `provider:model:tool`.
pub const TOOL_FEES_USD_PER_1K_CALLS: &[(&str, f64)] = &[
    ("openai:web_search", 10.0),
    ("openai:file_search", 2.5),
    ("anthropic:web_search", 10.0),
    ("anthropic:web_fetch", 0.0),
    ("google:google_search", 14.0),
    ("google:google_search_grounding_25", 35.0),
    ("perplexity:sonar:search_low", 5.0),
    ("perplexity:sonar:search_medium", 8.0),
    ("perplexity:sonar:search_high", 12.0),
    ("perplexity:sonar-pro:search_low", 6.0),
    ("perplexity:sonar-pro:search_medium", 10.0),
    ("perplexity:sonar-pro:search_high", 14.0),
    ("perplexity:sonar-reasoning-pro:search_low", 6.0),
    ("perplexity:sonar-reasoning-pro:search_medium", 10.0),
    ("perplexity:sonar-reasoning-pro:search_high", 14.0),
];

/// Providers whose response body carries a BILLED total in USD that may be
/// trusted in place of the gateway's own arithmetic. Empty by design: no
/// provider in this catalog returns one today (Perplexity explicitly
/// disclaims the figure it does return). Adding an id here is what switches
/// a provider onto the authoritative-total path.
pub const AUTHORITATIVE_COST_PROVIDERS: &[&str] = &[];
