---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noveum-gateway-ingress
  namespace: noveum
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    external-dns.alpha.kubernetes.io/hostname: gate.noveum.ai
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
spec:
  ingressClassName: kong
  rules:
    - host: gate.noveum.ai
      http:
        paths:
          - backend:
              service:
                name: noveum-ai-gateway-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - gate.noveum.ai
      secretName: noveum-tls-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: noveum-ai-gateway-svc
  namespace: noveum
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gate.noveum.ai
spec:
  selector:
    app: noveum-ai-gateway
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noveum-ai-gateway
  namespace: noveum
  labels:
    app: noveum-ai-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noveum-ai-gateway
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: noveum-ai-gateway
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      imagePullSecrets:
        - name: regcred
      containers:
        - name: noveum-ai-gateway
          image: noveum/noveum-ai-gateway:latest
          env:
            - name: RUST_LOG
              value: "info"
          ports:
            - containerPort: 3000
              name: http
          imagePullPolicy: Always
          resources:
            requests:
              memory: '512Mi'
              cpu: '512m'
            limits:
              memory: '1024Mi'
              cpu: '1024m'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: noveum-ai-gateway
  namespace: noveum
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: noveum-ai-gateway
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
